name: Actions - workflow 2 # name of the workflow 

on: [push]   

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: list files  # by default github will not clone your repo into your working directory. because not all workflows will use the files in the repository. inorder to clone we can use an action to do it 
        run: |
          pwd
          ls
      - name: clone repo to gibhub actions 
        uses: actions/checkout@v3
      - name: list files after checkout
        run: |
          pwd
          ls
      - id: greet123 # uses id to reference steps 
        name: simple js actions
        uses: actions/hello-world-javascript-action@v1 # we can use actions written locally or actions publicshed on github repo https://github.com/actions/hello-world-javascript-action or actions/hello-world-javascript-action@master
        with: # provide input to this action
          who-to-greet: amber
      - name: log greeting time
        run: echo "${{ steps.greet123.outputs.time }}"  #uses the id of steps, it will echo output of this action
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}