name: Shell Commands - workflow 1 # name of the workflow 

on: [push]   #events that will trigger this workflow to happen 


jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "hello world"
      - name: multiline script 
        run: |
          node -v
          npm -v
      - name: python command 
        run: |
          import platform 
          print(platform.processor())
        shell: python

